trigger:
  paths:
    include:
      - code/common
      - code/publisher

variables:
  - group: apim-automation
  - name: System.Debug
    value: true

stages:
  - stage: publish_publisher
    displayName: Publish publisher
    jobs:
      - job: publish_publisher
        displayName: Publish publisher
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: Install .NET Core SDK
            inputs:
              version: 7.x
              includePreviewVersions: true
          - task: DotNetCoreCLI@2
            displayName: Publish .NET Core application
            inputs:
              command: publish
              publishWebProjects: false
              projects: '$(Build.SourcesDirectory)/tools/code/publisher/publisher.csproj'
              arguments: '--output $(Build.ArtifactStagingDirectory) --runtime linux-x64 -p:PublishSingleFile=true'
              modifyOutputPath: false
              zipAfterPublish: false
          - task: UniversalPackages@0
            displayName: Publish publisher artifact
            inputs:
              command: publish
              vstsFeedPublish: $(System.TeamProject)/$(ARTIFACTS_FEED_NAME)
              vstsFeedPackagePublish: publisher
              packagePublishDescription: 'APIM publisher tool'
